### ISSUE TITLE
Latest git not building on boost-1.75.0

### ISSUE THREAD

**Issue by parazyd** [libbitcoin/libbitcoin-protocol#220]
Just so I don't forget, latest git HEAD (b8da139539c29fb904a42f42ffb1bb1dde89e85d at the time of writing) doesn't build with boost 1.75.0.

Errors follow:

```
In file included from /usr/include/boost/property_tree/json_parser/detail/read.hpp:13,
                 from /usr/include/boost/property_tree/json_parser.hpp:16,
                 from src/web/json_string.cpp:26:
/usr/include/boost/property_tree/json_parser/detail/parser.hpp: In member function 'void boost::property_tree::json_parser::detail::string_callback_adapter<Callbacks, Encoding, Iterator, std::input_iterator_tag>::process_codepoint(Sentinel, EncodingErrorFn)':
/usr/include/boost/property_tree/json_parser/detail/parser.hpp:217:59: error: 'boost::placeholders' has not been declared
  217 |                             boost::ref(callbacks), boost::placeholders::_1),
      |                                                           ^~~~~~~~~~~~
/usr/include/boost/property_tree/json_parser/detail/parser.hpp: In member function 'void boost::property_tree::json_parser::detail::parser<Callbacks, Encoding, Iterator, Sentinel>::feed(unsigned int)':
/usr/include/boost/property_tree/json_parser/detail/parser.hpp:520:79: error: 'boost::placeholders' has not been declared
  520 |                                                 boost::ref(callbacks), boost::placeholders::_1));
      |                                                                               ^~~~~~~~~~~~
make: *** [Makefile:1067: src/web/libbitcoin_protocol_la-json_string.lo] Error 1
make: *** Waiting for unfinished jobs....

```

**Comment by evoskuil** [comment]
https://github.com/libbitcoin/libbitcoin-system/pull/1174

**Comment by evoskuil** [comment]
I've integrated 1.72.0 as our minimum boost level for VC builds (the highest level with a NuGet package). Builds are clean on vc140 and vc141. There are still some issues in the Linux and macOS builds, due to boost breaking changes, but should be resolved soon. I suspect that will allow us to run up to 1.75.0. If so I'll enable that in some of the CI builds.

https://travis-ci.org/github/libbitcoin/libbitcoin-system/jobs/761563138

**Comment by evoskuil** [comment]
However, the error above appears to be due to the incorporation of std:: placeholders. This has been a problem in the past, which sources have to avoid (not a build issue.

**Comment by evoskuil** [comment]
Boost builds bumped in v4.
